openapi: 3.0.3
info:
  title: VirusTotal Clone Assignment
  description: |-
   Crowdstrike assignment Jaime Yu
  termsOfService: GPL3
  contact:
    email: jaime@jaimeyu.com
  license:
    name: AGPL3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  version: 1.0.0
externalDocs:
  description: Crowdstrike assignment
  url: http://swagger.io
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: report
    description: Scan Report
  - name: file
    description: file for scanning
  - name: user
    description: Operations about user
paths:
  /report/{hash}:
    get:
      tags:
        - report
      summary: Find Report by hash
      description: Returns a report by hash value
      operationId: getReportByHash
      parameters:
        - name: hash
          in: path
          description: Hash of the file (sha256)
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Report'
        '404':
          description: Report not found
  /scan/:
    post:
      tags:
        - file
      summary: uploads an file
      description: Upload a file to be scanned
      operationId: uploadFile
      parameters:
        - name: additionalMetadata
          in: query
          description: Additional Metadata
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    Report:
      required:
        - hash
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Filename maybe
        status:
          type: string
          description: Status of the report
        hash: 
          type: string
          description: The hash of the file
        incidents:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: name of the Antivirus
              result:
                type: string
                description: result of the scan
      xml:
        name: Report
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Report:
      description: Report object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Report'
        application/xml:
          schema:
            $ref: '#/components/schemas/Report'
  securitySchemes:
    # not used right now
    # API key should be for scan qoutas
    api_key:
      type: apiKey
      name: api_key
      in: header
